In [2]:
import numpy as np
import pandas as pd

In [15]:
# z = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([10,2,3,4])
# np.sum(a, axis=1)
(a * b[1:]) + b[0]
c = np.array([[1],[2],[3],[4]])
b*c.T

array([[10,  4,  9, 16]])

In [45]:
1 / (1+np.exp(a))

array([[0.26894142, 0.11920292, 0.04742587],
       [0.01798621, 0.00669285, 0.00247262]])

In [5]:
n = X_train.shape[1]             # for iris: n -> 4
size = X_train.shape[0]          # for iris: size -> 70
theta = np.zeros(shape=(n+1))    # n+1 array ; theta[0] will be treated like bias

In [6]:
pd.DataFrame(X_train).head(5)

0         1         2         3
0 -1.028056  0.727482 -0.926212 -1.093326
1 -1.328531  0.290368 -1.068706 -1.093326
2  0.774798  0.727482  1.139953  1.427755
3 -0.427105  0.727482 -1.068706 -1.093326
4 -0.727580 -1.676644  0.284988  0.347292

In [37]:
T = 100
y_hat = np.zeros(shape=(X_train.shape[0], T))
y_hat.shape

(70, 100)

In [37]:
T = 1000
alpha = 1e-3
for t in range(0,T):
    # z will contain linear combination of input features for all input samples
    z = np.zeros(shape=(size, n))
    z = (X_train * theta[1:]) + theta[0]

    # Storing z value for each input sample in theta_sum
    theta_sum = np.zeros(shape=(size))
    theta_sum = np.sum(z, axis=1)

    # Predicting y_hat for each input sample using Sigmoid function
    y_hat = 1 / (1 + np.exp(-theta_sum))

    # Calculate gradient of loss function wrt every theta
    del_L = np.zeros(shape=(n))
    for i in range(0,n):
        del_L[i] = np.sum((y_hat - y_train) * X_train[:,i].T)
    del_L /= size
    # print(pd.DataFrame(del_L))

    # Update the gradients
    theta[1:] = theta[1:] - (alpha * del_L)
    # print(pd.DataFrame(theta))

    # Print Loss according to your need, to check if its decreasing!
    if (t+1) % 100 == 0:
        Loss = np.sum((y_train * np.log(y_hat)) + ((1 - y_train) * np.log(1 - y_hat)))
        Loss /= (-size)
        print(f"Loss at the end of iteration {t+1}: {Loss}")

Loss at the end of iteration 100: 0.21280137558900147
Loss at the end of iteration 200: 0.2044449006313713
Loss at the end of iteration 300: 0.19671547323911343
Loss at the end of iteration 400: 0.1895472838539717
Loss at the end of iteration 500: 0.18288311481701233
Loss at the end of iteration 600: 0.17667302933915827
Loss at the end of iteration 700: 0.17087328515199263
Loss at the end of iteration 800: 0.1654454308317451
Loss at the end of iteration 900: 0.16035555115248074
Loss at the end of iteration 1000: 0.15557363445621344


In [17]:
X_train[2].shape

(4,)

In [35]:
t = 100
if t % 10 == 0:
    print("yo")
else:
    print("no man")

yo


In [40]:
z = np.zeros(shape=(size, n))
z = (X_test * theta[1:]) + theta[0]

# Storing z value for each input sample in theta_sum
theta_sum = np.zeros(shape=(X_test.shape[0]))
theta_sum = np.sum(z, axis=1)

# Predicting y_hat for each input sample using Sigmoid function
y_pred_scratch = 1 / (1 + np.exp(-theta_sum))

In [45]:
for i in range(0, y_pred_scratch.shape[0]):
    if y_pred_scratch[i] >= 0.5:
        y_pred_scratch[i] = 1
    else:
        y_pred_scratch[i] = 0
print(pd.DataFrame(y_pred_scratch))

      0
0   1.0
1   1.0
2   1.0
3   0.0
4   0.0
5   0.0
6   0.0
7   1.0
8   0.0
9   0.0
10  0.0
11  0.0
12  1.0
13  0.0
14  1.0
15  0.0
16  1.0
17  1.0
18  0.0
19  0.0
20  1.0
21  1.0
22  0.0
23  0.0
24  1.0
25  0.0
26  0.0
27  1.0
28  0.0
29  1.0


In [46]:
accuracy = accuracy_score(y_test, y_pred_scratch)
conf_matrix = confusion_matrix(y_test, y_pred_scratch)

print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 100.00%
Confusion Matrix:
[[17  0]
 [ 0 13]]


In [21]:
beta = 1e-2
beta

0.01

In [42]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset and prepare binary classification (class 0 vs class 1)
iris = load_iris()
X = iris.data[iris.target != 2]  # Only classes 0 and 1
y = iris.target[iris.target != 2]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 100.00%
Confusion Matrix:
[[17  0]
 [ 0 13]]


In [4]:
X_train.shape

(70, 4)

In [6]:
pd.DataFrame(X_train).head(5)

0         1         2         3
0 -1.028056  0.727482 -0.926212 -1.093326
1 -1.328531  0.290368 -1.068706 -1.093326
2  0.774798  0.727482  1.139953  1.427755
3 -0.427105  0.727482 -1.068706 -1.093326
4 -0.727580 -1.676644  0.284988  0.347292

In [11]:
y_train.shape

(70,)

In [44]:
pd.DataFrame(y_pred).head(5)

0
0  1
1  1
2  1
3  0
4  0