In [2]:
import pandas as pd
import numpy as np

In [3]:
# Import necessary libraries
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

# Step 1: Load the Breast Cancer dataset
cancer = datasets.load_breast_cancer()
X = cancer.data
y = cancer.target

# Step 2: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 3: Standardize the features (important for logistic regression)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
class LogisticRegressionFromScratch:
    def __init__(self, X_train: np.ndarray, 
                 y_train: np.ndarray,
                 alpha: float = 1e-3, 
                 T: int = 1000,
                 bias: float = 0):
        self.X_train = X_train
        self.size = X_train.shape[0]    # Number of input samples in X_train
        self.n = X_train.shape[1]       # Number of features in X_train
        self.y_train = y_train          
        self.alpha = alpha              # learning rate
        self.T = T                      # number of iterations
        self.bias = bias
        # Theta will contain weights used for finding linear combination of input features
        self.theta = np.zeros(shape=(self.n+1)) # n+1 array ; theta[0] will be treated like bias
        self.theta[0] = self.bias               # By default bias will be zero
        

    def fit_data(self):
        for t in range(0,self.T):
            # z will contain linear combination of input features for all input samples
            z = np.zeros(shape=(self.size, self.n))
            z = (self.X_train * self.theta[1:]) + self.theta[0]
        
            # Storing z value for each input sample in theta_sum
            theta_sum = np.zeros(shape=(self.size))
            theta_sum = np.sum(z, axis=1)
        
            # Predicting y_hat for each input sample using Sigmoid function
            y_hat = 1 / (1 + np.exp(-theta_sum))
        
            # Calculate gradient of loss function wrt every theta
            del_L = np.zeros(shape=(self.n))
            for i in range(0,self.n):
                del_L[i] = np.sum((y_hat - self.y_train) * self.X_train[:,i].T)
            del_L /= self.size
            # print(pd.DataFrame(del_L))
        
            # Update the weights used for linear combination using gradient descent
            self.theta[1:] = self.theta[1:] - (self.alpha * del_L)
            # print(pd.DataFrame(self.theta))
        
            # Print Loss according to your need, to check if its decreasing!
            if (t+1) % 100 == 0:
                Loss = np.sum((self.y_train * np.log(y_hat)) + ((1 - self.y_train) * np.log(1 - y_hat)))
                Loss /= (-self.size)
                print(f"Loss at the end of iteration {t+1}: {Loss}")
        

    def predict(self, X_test):
        z = np.zeros(shape=(self.size, self.n))
        z = (X_test * self.theta[1:]) + self.theta[0]
        
        # Storing z value for each input sample in theta_sum
        theta_sum = np.zeros(shape=(X_test.shape[0]))
        theta_sum = np.sum(z, axis=1)
        
        # Predicting y_hat for each input sample using Sigmoid function
        y_pred_scratch = 1 / (1 + np.exp(-theta_sum))

        for i in range(0, y_pred_scratch.shape[0]):
            if y_pred_scratch[i] >= 0.5:
                y_pred_scratch[i] = 1
            else:
                y_pred_scratch[i] = 0
        # print(pd.DataFrame(y_pred_scratch))
        return y_pred_scratch
        
        

In [8]:
model = LogisticRegressionFromScratch(X_train, y_train)
model.fit_data()
y_pred = model.predict(X_test)

Loss at the end of iteration 100: 0.5495188370090558
Loss at the end of iteration 200: 0.4649029058424642
Loss at the end of iteration 300: 0.4099834379516932
Loss at the end of iteration 400: 0.37128493495153403
Loss at the end of iteration 500: 0.34237175967430744
Loss at the end of iteration 600: 0.3198175607681469
Loss at the end of iteration 700: 0.3016363530410952
Loss at the end of iteration 800: 0.2865985763156334
Loss at the end of iteration 900: 0.27390214391425804
Loss at the end of iteration 1000: 0.2630011691352403


In [9]:
pd.DataFrame(y_pred).head(5)

0
0  1.0
1  0.0
2  0.0
3  1.0
4  1.0

In [10]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 95.32%
Confusion Matrix:
[[ 61   2]
 [  6 102]]


In [ ]:
# Increasing number of iterations helps in reducing loss value

In [11]:
model = LogisticRegressionFromScratch(X_train, y_train, T=2000)
model.fit_data()
y_pred = model.predict(X_test)

Loss at the end of iteration 100: 0.5495188370090558
Loss at the end of iteration 200: 0.4649029058424642
Loss at the end of iteration 300: 0.4099834379516932
Loss at the end of iteration 400: 0.37128493495153403
Loss at the end of iteration 500: 0.34237175967430744
Loss at the end of iteration 600: 0.3198175607681469
Loss at the end of iteration 700: 0.3016363530410952
Loss at the end of iteration 800: 0.2865985763156334
Loss at the end of iteration 900: 0.27390214391425804
Loss at the end of iteration 1000: 0.2630011691352403
Loss at the end of iteration 1100: 0.2535108693202501
Loss at the end of iteration 1200: 0.24515189673938187
Loss at the end of iteration 1300: 0.23771627475097115
Loss at the end of iteration 1400: 0.2310457561303717
Loss at the end of iteration 1500: 0.2250176224127801
Loss at the end of iteration 1600: 0.21953510090980713
Loss at the end of iteration 1700: 0.2145207370112907
Loss at the end of iteration 1800: 0.20991170980283833
Loss at the end of iteration 1

In [12]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 97.08%
Confusion Matrix:
[[ 62   1]
 [  4 104]]


In [21]:
beta = 1e-2
beta

0.01

In [42]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset and prepare binary classification (class 0 vs class 1)
iris = load_iris()
X = iris.data[iris.target != 2]  # Only classes 0 and 1
y = iris.target[iris.target != 2]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 100.00%
Confusion Matrix:
[[17  0]
 [ 0 13]]


In [4]:
X_train.shape

(70, 4)

In [6]:
pd.DataFrame(X_train).head(5)

0         1         2         3
0 -1.028056  0.727482 -0.926212 -1.093326
1 -1.328531  0.290368 -1.068706 -1.093326
2  0.774798  0.727482  1.139953  1.427755
3 -0.427105  0.727482 -1.068706 -1.093326
4 -0.727580 -1.676644  0.284988  0.347292

In [11]:
y_train.shape

(70,)

In [44]:
pd.DataFrame(y_pred).head(5)

0
0  1
1  1
2  1
3  0
4  0